method:
    name: "LeaderFollower" # chooses the agent to use

model:
    llm_call_style: "openai"
    name: "gpt-5-mini"
    leader: "right"  # "right" or "left"
    use_gt_obj_pos: False  # whether to use ground truth object positions at test time
    track_llm_stats: False  # when True, track and report LLM token usage and latency per episode

rlbench:
    task_name: "bimanual_push_box"
    cameras: [front,left_shoulder,right_shoulder,wrist] # overwritten at runtime in main.py
    tasks: [bimanual_push_box]
    demo_path: /my/demo/path
    episode_length: 25
    time_in_state: True
    headless: True

framework:
    gpu: 0
    logdir: /my/demo/logdir
    seed: 333
    start_seed: 0 # legacy, leave 0
    record_every_n: 5
    eval_envs: 1
    eval_from_eps_number: 0
    eval_episodes: 25
    eval_save_metrics: True
    repeat_eval: 1 # how many times to repeat the evaluation over each task, then report avg and std

cinematic_recorder:
    enabled: False
    camera_resolution: [1280, 720]
    fps: 30
    rotate_speed: 0.005
    save_path: './videos/'